# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jk-ArtSpace-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jk-ArtSpace-Project

  target 'Jk-ArtSpace-ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
